events {
    worker_connections 1024;
}

http {
    # Configuração de Proxy para o Portal
    server {
        listen 80;
        server_name portal.cliente1.local;

        location / {
            proxy_pass http://portal-c1:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Configuração de Proxy para o Hotsite
    server {
        listen 80;
        server_name hotsite.cliente1.local;

        location / {
            proxy_pass http://hotsite-c1:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Configuração de Proxy para o Sign
    server {
        listen 80;
        server_name sign.cliente1.local;

        location / {
