events {
    worker_connections 1024;
}

http {
    # --- CONFIGURAÇÃO DO PROVEDOR (ISP) ---
    server {
        listen 80;
        server_name potiguarnet.provedor.asa.br;

        location / {
            proxy_pass http://portal:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # --- REDIRECIONAMENTO PARA O CLIENTE 1 ---
    # O ISP recebe a requisição dos domínios do cliente e repassa para o proxy dele
    server {
        listen 80;
        server_name portal.cliente1.com.br hotsite.cliente1.com.br sign.cliente1.com.br;

        location / {
            # Importante: proxy-reverso-c1 deve ser o container_name 
            # definido no compose do Cliente 1
            proxy_pass http://proxy-reverso-c1:80; 

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
