events {}

http {
  server {
    listen 80;
    server_name potiguarnet.provedor.asa.br;

    location / {
      proxy_pass http://portal:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}

# --- COMPLEMENTO: REDIRECIONAMENTO PARA O CLIENTE 1 ---
    # Este bloco delega a responsabilidade para o Proxy do Cliente 1
    server {
        listen 80;
        server_name portal.cliente1.com.br hotsite.cliente1.com.br sign.cliente1.com.br;

        location / {
            # O ISP apenas "passa a bola" para o proxy do cliente
            proxy_pass http://proxy-reverso-c1:80; 

            # Mantém os dados originais da requisição
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
